#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.7.2 on Tue Oct 11 10:13:15 2016
#

import wx
import time
# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class LogFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: LogFrame.__init__
        wx.Frame.__init__(self, *args, **kwds)
        #self.historyList = wx.ListCtrl(self, wx.ID_ANY)
	self.historyList = wx.ListCtrl(self, size=(-1,100),
                         style=wx.LC_REPORT)
                                             
	self.historyList.InsertColumn(0,'Log', width=300)
	self.historyList.InsertColumn(1,'Date', width=100)
	self.historyList.InsertColumn(2,'Time', width=50)
        self.text_ctrl_1 = wx.TextCtrl(self, wx.ID_ANY, _("Enter your log here"), style=wx.TE_CHARWRAP | wx.TE_MULTILINE | wx.TE_PROCESS_ENTER)
        self.logbutton = wx.Button(self, wx.ID_ANY, _("Log"))
	self.index = 0
        self.__set_properties()
        self.__do_layout()
	self.logbutton.Bind(wx.EVT_BUTTON, self.add_line)
	self.historyList.Bind(wx.EVT_LIST_ITEM_ACTIVATED, self.showLog)
	self.historyList.Bind(wx.EVT_LIST_ITEM_SELECTED, self.onSelect)
        # end wxGlade
    def onSelect(self, event):
	
	row = event.m_itemIndex
	col = 0
	item = self.historyList.GetItem(itemId=row, col=col)
	self.logText = item.GetText()
    def showLog(self, event):

	frame = ShowLog(self.logText)
	frame.Show()
    def add_line(self, event):
	message=self.text_ctrl_1.GetValue()
	timestamp = time.strftime("%H:%M")
	date = time.strftime("%d %b %Y")
	self.historyList.InsertStringItem(self.index, message)
	self.historyList.SetStringItem(self.index, 2, timestamp)
	self.historyList.SetStringItem(self.index, 1, date)
	self.index +=1
	self.writeToLog(message, date, timestamp)
	self.text_ctrl_1.Clear()
    def writeToLog(self, message, date, timestamp):
	openFile = open('Logs','a')
	writemessage = ""
	header = message.find('\n')
	if header != -1:
	    startmessage = message [0:header]
	    openFile.write("%s\t%s\t%s%s\n\n"%(startmessage, date, timestamp, message[header:]))
	else:
	    openFile.write("%s\t%s\t%s\n\n"%(message, date, timestamp))
	openFile.close()
    def __set_properties(self):
        # begin wxGlade: LogFrame.__set_properties
        self.SetTitle(_("Automatic Log System"))
        self.SetSize((450, 250))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: LogFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(self.historyList, 2, wx.EXPAND, 0)
        sizer_2.Add(self.text_ctrl_1, 4, wx.EXPAND, 4)
        sizer_2.Add(self.logbutton, 1, wx.ALIGN_RIGHT | wx.EXPAND, 0)
        sizer_1.Add(sizer_2, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

class ShowLog(wx.Frame):
    def __init__(self, log):
	self.log = log	
	wx.Frame.__init__(self, None, title="Selected Log")
        panel = wx.Panel(self)
        txt = wx.StaticText(panel, label=self.log)		
# end of class LogFrame
if __name__ == "__main__":
    gettext.install("logApp") # replace with the appropriate catalog name

    logApp = wx.PySimpleApp()
    frame_1 = LogFrame(None, wx.ID_ANY, "")
    logApp.SetTopWindow(frame_1)
    frame_1.Show()
    logApp.MainLoop()
